<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Version>0.2.0-preview.3</Version>
    <Authors>TBankNet.Multisplit contributors</Authors>
    <PackageProjectUrl>https://github.com/ai-iskuzhin/TBankNet.Multisplit</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ai-iskuzhin/TBankNet.Multisplit</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>tbank;tinkoff;acquiring;multisplit;shops</PackageTags>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
